services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - tracker-app-net

  frontend:
    build: ./frontend
    ports:
      - "3500:80"
    depends_on:
      - backend
    networks:
      - tracker-app-net
    environment:
      BACKEND_URL: "backend:8000/tasks"   # for local dev and test only

networks:
  tracker-app-net:
