version: '3'

services:
  backend:
    image: 654654484434.dkr.ecr.us-east-1.amazonaws.com/staging-backend-repo:latest
    expose:
      - 8000
    networks:
      - tracker-app-net

  frontend:
    image: 654654484434.dkr.ecr.us-east-1.amazonaws.com/staging-frontend-repo:latest
    ports:
      - "3500:80"
    depends_on:
      - backend
    networks:
      - tracker-app-net

networks:
  tracker-app-net:
