services:
  backend:
    build: ./backend
    ports:
      - "8000:8000" 
      - "8001:8001"
    networks:
      - tracker-app-net

  frontend:
    build: ./frontend
    ports:
      - "3500:80"
    depends_on:
      - backend
    networks:
      - tracker-app-net

networks:
  tracker-app-net: