services:
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - tracker-app-net
    restart: always

  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tracker-app-net
    environment:
      BACKEND_URL:  "${FRONTEND_EXTERNAL_BACKEND_URL}"
    restart: always


networks:
  tracker-app-net:
