version: '3'

services:
  backend:
    build: ./backend
    # ports:
    #   - "8000:8000" # For testing locally
    expose:
      - 8000
    networks:
      - tracker-app-net

  frontend:
    build: ./frontend
    ports:
      - "3500:80"
    depends_on:
      - backend
    networks:
      - tracker-app-net

networks:
  tracker-app-net: