version: '3'

services:
  backend:
    image: ${BACKEND_IMAGE}
    expose:
      - 8000
    networks:
      - tracker-app-net

  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "3500:80"
    depends_on:
      - backend
    networks:
      - tracker-app-net

networks:
  tracker-app-net:
