environment        = "production"
instance_type      = "t2.micro"
key_name           = "Godson-kp"
vpc_cidr           = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
my_ip              = "0.0.0.0/0"
