name: CI/CD - Staging

on:
  # push:
  #   branches:
  #     - develop
  workflow_dispatch:

jobs:
  test_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies and Run Tests
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx
          pytest ./tests/

  deploy_staging:
    needs: test_backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Staging Images
        run: |
          IMAGE_TAG=${GITHUB_SHA}

          # Backend
          docker build -t backend ./backend
          docker tag backend:latest ${{ steps.login-ecr.outputs.registry }}/staging-backend-repo:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/staging-backend-repo:$IMAGE_TAG
          docker tag backend:latest ${{ steps.login-ecr.outputs.registry }}/staging-backend-repo:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/staging-backend-repo:latest

          # Frontend
          docker build -t frontend ./frontend
          docker tag frontend:latest ${{ steps.login-ecr.outputs.registry }}/staging-frontend-repo:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/staging-frontend-repo:$IMAGE_TAG
          docker tag frontend:latest ${{ steps.login-ecr.outputs.registry }}/staging-frontend-repo:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/staging-frontend-repo:latest

      - name: Create .env for Staging
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          echo "BACKEND_IMAGE=${{ steps.login-ecr.outputs.registry }}/staging-backend-repo:$IMAGE_TAG" > .env
          echo "FRONTEND_IMAGE=${{ steps.login-ecr.outputs.registry }}/staging-frontend-repo:$IMAGE_TAG" >> .env
          echo "FRONTEND_EXTERNAL_BACKEND_URL=http://${{ secrets.STAGING_EC2_HOST }}:8000" >> .env

      - name: Deploy to EC2 (Staging)
        env:
          HOST: ${{ secrets.STAGING_EC2_HOST }}
          USERNAME: ubuntu
          KEY: ${{ secrets.STAGING_EC2_SSH_KEY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem

          # Copy docker-compose + env file
          scp -o StrictHostKeyChecking=no -i key.pem docker-compose.yaml .env $USERNAME@$HOST:/home/ubuntu/tracker-app/

          # SSH into EC2 and deploy
          ssh -o StrictHostKeyChecking=no -i key.pem $USERNAME@$HOST << 'EOF'
          set -e
          cd /home/ubuntu/tracker-app

          echo ">>> Updating package lists..."
          sudo apt-get update -y

          echo ">>> Installing essential packages..."
          sudo apt-get install -y unzip curl wget jq ca-certificates gnupg lsb-release

          echo ">>> Installing Docker & docker-compose..."
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo usermod -aG docker ubuntu

          echo ">>> Installing AWS CLI v2..."
          if ! command -v aws &> /dev/null; then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            rm -rf awscliv2.zip aws
          fi

          echo ">>> Authenticating Docker to ECR..."
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY

          echo ">>> Pulling and restarting containers..."
          docker-compose --env-file .env pull
          docker-compose --env-file .env down
          docker-compose --env-file .env up -d

          echo ">>> Waiting for backend to become healthy..."
          sleep 10
          curl -f http://localhost:8000/health || (echo "Backend health check failed!" && exit 1)
          EOF
