name: Deploy Logging Stack to Staging

on:
  workflow_dispatch:    # Manual trigger only

jobs:
  deploy_logging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Logging to EC2
        env:
          HOST: ${{ secrets.STAGING_EC2_HOST }}
          USERNAME: ubuntu
          KEY: ${{ secrets.STAGING_EC2_SSH_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem

          # Copy logging folder
          scp -o StrictHostKeyChecking=no -i key.pem -r logging $USERNAME@$HOST:/home/ubuntu/logging/

          # SSH to EC2 and start containers
          ssh -o StrictHostKeyChecking=no -i key.pem $USERNAME@$HOST << EOF
          set -e
          cd /home/ubuntu/logging
          docker compose pull || true
          docker compose down
          docker compose up -d
          EOF
