name: Terraform Provisioning

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (staging or production)'
        required: true
        default: 'staging'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Environment Directory
        run: echo "TF_DIR=infra_config/${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform -chdir=$TF_DIR init

      - name: Terraform Plan
        run: terraform -chdir=$TF_DIR plan 

      - name: Terraform Apply
        run: terraform -chdir=$TF_DIR apply -auto-approve 
